version: '2'
services:
    httpd_tomee:
      image: httpd
      container_name: httpd_tomee
      ports:
        - 80:80
      volumes:
        - ../common/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./httpd-load-balancer.conf:/usr/local/apache2/conf/extra/httpd-load-balancer-conf

    tomee-node-1:
      image: tomee:9.1-jre11-Semeru-webprofile
      container_name: tomee-node-1
      hostname: tomee-node-1
      ports:
        - 8081:8080
      volumes:
        - ./server.xml:/usr/local/tomee/conf/server.xml
        - ../common/logging.properties:/usr/local/tomee/conf/logging.properties
        - ../target/session-replication.war:/usr/local/tomee/webapps/session-replication.war
      environment:
        - CATALINA_OPTS=-Dload-balancer.route=node1
      depends_on:
        - httpd_tomee

    tomee-node-2:
      image: tomee:9.1-jre11-Semeru-webprofile
      container_name: tomee-node-2
      hostname: tomee-node-2
      ports:
        - 8082:8080
      volumes:
         - ./server.xml:/usr/local/tomee/conf/server.xml
         - ../common/logging.properties:/usr/local/tomee/conf/logging.properties
         - ../target/session-replication.war:/usr/local/tomee/webapps/session-replication.war
      environment:
        - CATALINA_OPTS=-Dload-balancer.route=node2
      depends_on:
        - httpd_tomee
